# general configuration
url: http://dhashe.com
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/photo.png"
  # author will appear under the avatar (optional)
  author: "David Hashe"
  # tagline will appear under the title (optional)
  tagline: "Undergraduate student at <br /> <a href='http://cmu.edu'>Carnegie Mellon University</a>"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
